Milestone 3: Leaderboard final touches
odhiambo-ed/Learderboard-White3d pull request #3
Opened 2022-04-07 06:35 UTC by white3d

In this milestone, I did the following:

    - Added more style.
    - Did final touches.

2022-04-07 07:16 UTC, Deepakdanger requested changes
Hi @white3d, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

- [ ] I would recommend to update the `live link` to make the README professional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-07 07:16 UTC, Deepakdanger commented on src/index.html
> +                    </div> -->
- [ ] I would recommend removing the commented code to make  the codebase cleaner.

2022-04-07 11:20 UTC, aimemalaika requested changes
Hi @white3d  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

 ## Required Changes ♻️

- [ ] Kindly update your live link.

- [ ] After cloning and installing dependencies I am having difficulties to run the project due to this error `Module not found: Error: Can't resolve '@popperjs/core' in '/Users/aimemalaika/Documents/Microverse/reviews/Learderboard-White3d/node_modules/bootstrap/dist/js'`, Kindly solve the issue or document in your PR description the way to solve the issue.
![Screen Shot 2022-04-07 at 13 14 07](https://user-images.githubusercontent.com/28307960/162187526-8c7e0d68-fbe2-4661-9716-5e0db9420128.png)



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 07:45 UTC, Kingstalux approved these changes
Hi @white3d,
# Status: Approved ✔️ ✔️ ✔️ 
 
![Gu2dpSp0qee4C710M5kVsWN425J3-vv2w52by6](https://user-images.githubusercontent.com/85113567/162389600-a49d0977-b35f-4e8f-a798-1ab519b8bd6b.gif)


Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-08 08:15 UTC, merged